version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: em-backend
    restart: unless-stopped
    networks:
      - em-network
    expose:
      - "8080"  # порт не публикуется наружу

  nginx:
    image: nginx:1.25-alpine
    container_name: em-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - em-network
    depends_on:
      - backend

networks:
  em-network:
    name: em-network
    driver: bridge